# Generated by Django 4.1.1 on 2023-03-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_uz', models.CharField(blank=True, max_length=255)),
                ('head_ru', models.CharField(blank=True, max_length=255)),
                ('text_uz', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='img/tea/')),
            ],
        ),
        migrations.CreateModel(
            name='About_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_uz', models.CharField(blank=True, max_length=255)),
                ('head_ru', models.CharField(blank=True, max_length=255)),
                ('body_uz', models.CharField(blank=True, max_length=255)),
                ('body_ru', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image_background', models.ImageField(upload_to='img/faqts_tea/')),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_text_uz', models.TextField(blank=True)),
                ('form_text_ru', models.TextField(blank=True)),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Company_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_uz', models.CharField(blank=True, max_length=50)),
                ('head_ru', models.CharField(blank=True, max_length=50)),
                ('body_uz', models.TextField(blank=True)),
                ('body_ru', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='img/head/')),
            ],
        ),
        migrations.CreateModel(
            name='Faqts_tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_uz', models.CharField(blank=True, max_length=255)),
                ('head_ru', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField()),
                ('text_uz', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='img/price_tea/')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField(blank=True)),
                ('text_ru', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='img/about_tea/')),
            ],
        ),
    ]
